Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mriqc_learn.viz import metrics
from mriqc_learn.models.preprocess import SiteRobustScaler
from mriqc_learn.datasets import load_dataset

(train_x, train_y), _ = load_dataset(split_strategy="none")
train_x = train_x.drop(columns = ['size_x', 'size_y', 'size_z', 'spacing_x', 'spacing_y', 'spacing_z'], inplace = False)
numeric_columns = train_x.columns.tolist()

# Harmonize between sites
scaled_x = SiteRobustScaler(unit_variance=True).fit_transform(train_x)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 10>[0;34m()[0m
[1;32m      7[0m numeric_columns [38;5;241m=[39m train_x[38;5;241m.[39mcolumns[38;5;241m.[39mtolist()
[1;32m      9[0m [38;5;66;03m# Harmonize between sites[39;00m
[0;32m---> 10[0m scaled_x [38;5;241m=[39m [43mSiteRobustScaler[49m[43m([49m[43munit_variance[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m[38;5;241;43m.[39;49m[43mfit_transform[49m[43m([49m[43mtrain_x[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/sklearn/base.py:852[0m, in [0;36mTransformerMixin.fit_transform[0;34m(self, X, y, **fit_params)[0m
[1;32m    848[0m [38;5;66;03m# non-optimized default implementation; override when a better[39;00m
[1;32m    849[0m [38;5;66;03m# method is possible for a given clustering algorithm[39;00m
[1;32m    850[0m [38;5;28;01mif[39;00m y [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    851[0m     [38;5;66;03m# fit method of arity 1 (unsupervised transformation)[39;00m
[0;32m--> 852[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfit_params[49m[43m)[49m[38;5;241m.[39mtransform(X)
[1;32m    853[0m [38;5;28;01melse[39;00m:
[1;32m    854[0m     [38;5;66;03m# fit method of arity 2 (supervised transformation)[39;00m
[1;32m    855[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mfit(X, y, [38;5;241m*[39m[38;5;241m*[39mfit_params)[38;5;241m.[39mtransform(X)

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/mriqc_learn/models/preprocess.py:128[0m, in [0;36mSiteRobustScaler.fit[0;34m(self, X, y)[0m
[1;32m    127[0m [38;5;28;01mdef[39;00m [38;5;21mfit[39m([38;5;28mself[39m, X, y[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 128[0m     sites [38;5;241m=[39m [43mX[49m[43m[[49m[43m[[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgroupby[49m[43m][49m[43m][49m[38;5;241m.[39mvalues[38;5;241m.[39msqueeze()
[1;32m    129[0m     X_input [38;5;241m=[39m X[38;5;241m.[39mdrop([[38;5;28mself[39m[38;5;241m.[39mgroupby], axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m    131[0m     [38;5;28mself[39m[38;5;241m.[39mscalers_ [38;5;241m=[39m {}

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/core/frame.py:3511[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   3509[0m     [38;5;28;01mif[39;00m is_iterator(key):
[1;32m   3510[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 3511[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[1;32m   3513[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[1;32m   3514[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/core/indexes/base.py:5782[0m, in [0;36mIndex._get_indexer_strict[0;34m(self, key, axis_name)[0m
[1;32m   5779[0m [38;5;28;01melse[39;00m:
[1;32m   5780[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[0;32m-> 5782[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   5784[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[1;32m   5785[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[1;32m   5786[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/pandas/core/indexes/base.py:5842[0m, in [0;36mIndex._raise_if_missing[0;34m(self, key, indexer, axis_name)[0m
[1;32m   5840[0m     [38;5;28;01mif[39;00m use_interval_msg:
[1;32m   5841[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 5842[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[1;32m   5844[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m   5845[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[0;31mKeyError[0m: "None of [Index(['site'], dtype='object')] are in the [columns]"
KeyError: "None of [Index(['site'], dtype='object')] are in the [columns]"

